-- ==========================================================================
-- 0035_palette_option_code.sql -- BWS prints an option's own code INSIDE the
-- option, and the label has to keep it.
--
-- WHY. 0030 seeded the five BWS-owned palettes as rows with zero options and a
-- null `synced_at`, because this app had never been given the lists. Max
-- logged into BWS on 2026-09-22 and they were captured -- all 84 standard
-- specification fields read read-only from the Palette options box on each
-- /edit page, into docs/plans/bws-palette-capture-2026-09-22.json, with the
-- capture note beside it. db/seed/0011 is the seed; this is the one column it
-- needs that 0030 did not have.
--
-- ---- THE CODE IS INSIDE THE STRING --------------------------------------
--
-- One palette, Stud spec, writes its options like this:
--
--   Standard - French Natural | BWE Code: U1660-6031
--   Large - Polished Nickel
--   Standard - Antique on Brass | BWE Code: U1660-9431 - Shank Oxidized
--
-- Eight of the thirteen carry a code and five do not, and two carry a further
-- qualifier AFTER the code. So the code cannot be split off by taking the
-- text before a hyphen, and the half-measures both lose something real:
-- storing only the code loses "Standard - French Natural", which is the half a
-- reviewer recognises, and storing only the prose loses the part a purchase
-- order is raised against.
--
-- `label` and `value` therefore keep BWS's line WHOLE -- what BWS shows is
-- what we show, which is what makes a value checkable against BWS -- and this
-- column carries the code as well, for the case the whole point of parsing it
-- is: a drawing that quotes `U1660-6031` and nothing else.
--
-- Nullable, because most options have no code and inventing one is the
-- opposite of the exercise. It is BWS's identifier, not ours, so nothing in
-- this app ever generates one.
--
-- ---- WHY NOT A UNIQUE INDEX ---------------------------------------------
--
-- Tempting, and wrong twice over. Across palettes, nothing says two BWS
-- vocabularies cannot reuse a code -- they are BWS's namespace, not ours.
-- Within one, a unique index would make a future re-sync fail at the migration
-- rather than in the diff a person reads, and the sync rule is that a change
-- upstream is REPORTED, never silently applied or silently refused. The seed
-- asserts uniqueness where it inserts, which is where a person can act on it.
-- ==========================================================================
begin;

alter table spec_palette_options add column code text;

comment on column spec_palette_options.code is
  'BWS''s own code for the option, parsed out of its label where BWS printed one (Stud spec: "... | BWE Code: U1660-6031"). Null is the normal case. The label keeps the whole string regardless; this is for matching a document that quotes the code alone. Never generated by this app.';

-- A code that is present must say something. A blank string here would read as
-- "there is a code" to every `is not null` test that follows.
alter table spec_palette_options add constraint spec_palette_options_code_not_blank
  check (code is null or btrim(code) <> '');

commit;
