// The closed lists a spec field offers, and the five this app does not hold.
//
// ============================================================================
// THE MODEL NEVER PICKS AN OPTION.
//
// house/conventions.md §6: the fuzzy step and the exact step are separate. The
// model reads a document and decides nothing; resolving what it read to a
// palette value happens afterwards, deterministically, in code, against this
// app's own register. `normalisePaletteValue` is that step, and it returns
// NULL on anything it does not recognise rather than reaching for the nearest
// option — an unresolved value is a visible flag, never a plausible-looking
// wrong answer.
//
// ---- THE FIVE BWS PALETTES ARE HELD, AS OF 2026-09-22 -------------------
//
// Matthew's matrix names "From BWS timber finish palette" and four more like
// it, and for four months this app held none of them: they were seeded as rows
// with zero options and a null `synced_at`, the field stayed free text, and
// the screen said so in words. They were captured read-only from BWS on
// 2026-09-22 (db/seed/0011, docs/plans/bws-palette-capture-2026-09-22.json)
// and are now real lists -- timber 35, metal 15, seat build 27, back cushion
// 6, stud 13.
//
// `unheldPaletteNote` and the `isOfferable` branch STAY. Nothing in this app
// is unheld today, and the next BWS palette somebody points a gate at will be,
// between the gate landing and the sync. A screen that has forgotten how to
// say "BWS owns this and we do not have it" offers an empty dropdown instead,
// which reads as broken and gets typed around.
//
// What has NOT changed: do not invent one. FMT-GEN-01, and a guessed finish
// list is the one kind of wrong answer nothing downstream would question. The
// five are a READ of BWS's own box, and the seed's guard refuses options on a
// BWS palette with no `synced_at` behind them.
// ============================================================================

export type PaletteOwner = "app" | "bws";

export type PaletteOption = {
  /**
   * `spec_palette_options.id`, which a BW standard names (0041). Optional: a
   * fixture or a screen that only ever shows a list need not carry it, and
   * the server resolves it from the value whenever it writes one -- a client
   * never gets to say which option a row points at.
   */
  id?: string;
  value: string;
  label: string;
  sortOrder: number;
  isDefault: boolean;
  /**
   * BWS's own code for the option, where BWS printed one inside the label.
   * Null is the normal case -- only Stud spec carries them, 8 of its 13. The
   * label keeps the whole string either way; this is here so a document that
   * quotes `U1660-6031` and nothing else can still be resolved. Never
   * generated by this app.
   */
  code: string | null;
};

export type Palette = {
  key: string;
  name: string;
  owner: PaletteOwner;
  allowsFreeText: boolean;
  sourceNote: string | null;
  /** Null means never synced. For a BWS-owned palette that is the point. */
  syncedAt: string | null;
  options: PaletteOption[];
};

/**
 * A `spec_palettes` row as the database names its columns — and as two screens
 * already read it out of their payloads.
 *
 * Kept apart from `Palette` on purpose. `src/lib/palette-load.ts` returns this
 * shape because the record and infill screens fold it themselves and changing
 * their payload is a change to those screens, not a refactor of the loader.
 */
export type PaletteRow = {
  key: string;
  name: string;
  owner: PaletteOwner;
  allows_free_text: boolean;
  source_note: string | null;
  synced_at: string | null;
  options: PaletteOption[] | null;
};

/**
 * The one fold from the row to the domain type.
 *
 * It exists so that a caller which wants a `Palette` -- the drawings review,
 * which is handed one attached to its field register -- does not write a third
 * copy of this mapping. `options` is coalesced to an empty array by the query
 * and again here: a palette with no options is a real state the screens have
 * to say out loud, and `undefined` there would make `isOfferable` throw
 * instead.
 */
export function paletteFromRow(row: PaletteRow): Palette {
  return {
    key: row.key,
    name: row.name,
    owner: row.owner,
    allowsFreeText: Boolean(row.allows_free_text),
    sourceNote: row.source_note,
    syncedAt: row.synced_at,
    options: row.options ?? [],
  };
}

/** A palette this app can actually offer as a list. */
export function isOfferable(palette: Palette): boolean {
  return palette.options.length > 0;
}

/**
 * What a screen says where a palette exists and its options do not.
 *
 * Said in words rather than shown as an empty dropdown: a select with one
 * option reads as broken, and a reviewer who thinks the control is broken
 * types something into the next box instead of asking for the list.
 */
export function unheldPaletteNote(palette: Palette): string {
  return `${palette.name} — BWS owns this list and it is not loaded here, so this stays free text.`;
}

/**
 * A palette's name folded into the middle of a sentence.
 *
 * Lower-cased, so "Not one of the swivel mechanism options" reads, EXCEPT
 * where the name opens with an acronym -- "the bws timber finish palette"
 * is a typo on screen, and BWS owns five of the eleven. Only the first word
 * is examined: it is the only one the sentence position affects.
 */
export function sentenceCasePaletteName(name: string): string {
  const [first, ...rest] = name.split(" ");
  if (!first) return name;
  const isAcronym = first.length > 1 && first === first.toUpperCase() && /[A-Z]/.test(first);
  return [isAcronym ? first : first.toLowerCase(), ...rest.map((w) => w.toLowerCase())].join(" ");
}

/**
 * What a screen says about a written value the palette does not hold.
 *
 * ONE SENTENCE, TWO SCREENS. The record's `AnswerValue` has said this since
 * 0030 and the drawings review says it from 2026-09-22, and they must say it
 * identically: a reviewer who reads "Kept as written" on one screen and
 * something else on the other has to work out whether the two mean the same
 * thing. The TONE is each screen's own -- amber where a settled answer sits
 * outside its list, neutral at intake, where it is the normal case and not a
 * problem: `npm run palette:gap` on the sandbox, 2026-09-22, reads 0 of 81
 * value-bearing callouts matching an option.
 */
export function offPaletteNote(palette: Palette): string {
  return `Not one of the ${sentenceCasePaletteName(palette.name)} options. Kept as written.`;
}

/**
 * The palette a staged row's BWS field offers, or null.
 *
 * ============================================================================
 * THE LINK IS THE FIELD, AND THE FIELD REGISTER IS WHERE IT IS CARRIED.
 *
 * A drawings observation carries a `spec_fields.id` -- never a requirement, a
 * category or a local key, because a callout is what a PAGE said and not an
 * answer to a checklist question. The palette is attached to the field
 * register the screen already threads (`withPalettes` in `palette-load.ts`),
 * so this is a lookup and not a second resolution.
 *
 * A ROW WITH NO FIELD GETS NOTHING, which is most of them: a note, an
 * unplaced callout and every dimension have no BWS field, and COM 1/2/3 have
 * no palette. Null here means the row renders exactly as it did before
 * palettes reached this screen.
 * ============================================================================
 */
export function paletteForField(
  fields: readonly { id: string; palette?: Palette | null }[],
  specFieldId: string | null | undefined,
): Palette | null {
  if (!specFieldId) return null;
  return fields.find((field) => field.id === specFieldId)?.palette ?? null;
}

/** The value a control preselects. NEVER an answer: `missing` means nobody has looked. */
export function defaultOption(palette: Palette): PaletteOption | null {
  return palette.options.find((option) => option.isDefault) ?? null;
}

/**
 * Fold a written value onto a palette option, or return null.
 *
 * Case and whitespace only, plus the punctuation a person types differently
 * from the way it was seeded — an en dash for a hyphen, a degree sign, a
 * doubled space. Deliberately NOT clever: `normaliseFinishCode` keeps
 * `CH-01.1` and `CH-01-1` apart for the same reason, because a normaliser
 * clever enough to merge two spellings is clever enough to merge two things
 * somebody meant to keep separate, and there is no way back.
 */
export function normalisePaletteValue(palette: Palette, raw: string | null): string | null {
  const wanted = comparisonKey(raw);
  if (!wanted) return null;
  const hit = palette.options.find(
    (option) =>
      comparisonKey(option.value) === wanted ||
      comparisonKey(option.label) === wanted ||
      // BWS's own code, where it has one. This is still the EXACT step, not a
      // widening: `U1660-6031` is BWS's identifier for exactly one stud and
      // matching it is a lookup, not a guess. A drawing that quotes the code
      // alone is the case the column exists for.
      (option.code !== null && comparisonKey(option.code) === wanted),
  );
  return hit ? hit.value : null;
}

/**
 * The option a written value names, whole -- with its id -- or null.
 *
 * `normalisePaletteValue`'s exact step and nothing looser; it returns the
 * option so a writer can record WHICH one, where that function returns only
 * the value a select sits on.
 */
export function paletteOptionFor(palette: Palette, raw: string | null): PaletteOption | null {
  const value = normalisePaletteValue(palette, raw);
  return value === null ? null : (palette.options.find((option) => option.value === value) ?? null);
}

/** The single comparison key. Every call site uses this rather than `===` on a raw string. */
export function comparisonKey(raw: string | null): string {
  if (!raw) return "";
  return raw
    .replace(/[‐-―]/g, "-")   // every dash BWS, Word and a designer can produce
    .replace(/°/g, "")              // 360° and 360 are the same mechanism
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

/**
 * Is this written value one the palette holds?
 *
 * Used by a screen to decide whether to show the select on the option or to
 * show it as "Other". A value outside a palette that ALLOWS free text is fine
 * and is shown as itself; one outside a palette that does not is a flag.
 */
export function isOffPalette(palette: Palette, raw: string | null): boolean {
  if (!raw?.trim()) return false;
  if (!isOfferable(palette)) return false;
  return normalisePaletteValue(palette, raw) === null;
}
