import { describe, expect, it } from "vitest";
import {
  countPdfPages,
  MAX_MODEL_PDF_PAGES,
  prepareDocumentSource,
  spreadsheetSheetsToText,
} from "@/lib/intake-source";
import { intakeSourceKind } from "@/lib/intake-source-types";
import { buildPdfOfPages } from "../fixtures/build-pdf.mjs";

describe("intake spreadsheet sources", () => {
  it("recognises supported extensions without trusting a mismatched MIME type", () => {
    expect(intakeSourceKind("doc.xlsx", "application/octet-stream")).toBe("xlsx");
    expect(intakeSourceKind("doc.csv", "text/plain")).toBe("csv");
    expect(intakeSourceKind("doc.xls", "application/vnd.ms-excel")).toBe("unsupported");
    expect(intakeSourceKind("doc.exe", "application/pdf")).toBe("unsupported");
  });

  it("preserves sheet names, row order, blanks and typed values", () => {
    const text = spreadsheetSheetsToText([
      {
        sheet: "Furniture",
        data: [
          ["Code", "Description", "Quantity"],
          ["01-100", "Lounge chair", 2],
          ["01-100A", null, 14.5],
        ],
      },
      { sheet: "Notes", data: [["FR required", true]] },
    ]);

    expect(text).toContain('<sheet name="Furniture">');
    expect(text).toContain('["01-100A",null,14.5]');
    expect(text).toContain('<sheet name="Notes">\n["FR required",true]');
  });

  it("parses quoted CSV rows into the spreadsheet source format", async () => {
    const source = await prepareDocumentSource(
      Buffer.from('Code,Description,Quantity\r\n01-100,"Chair, lounge",2\r\n'),
      "doc.csv",
      "text/csv",
    );

    expect(source.type).toBe("spreadsheet");
    if (source.type === "spreadsheet") {
      expect(source.text).toContain('["01-100","Chair, lounge","2"]');
    }
  });

  it("keeps PDFs as base64 input", async () => {
    const source = await prepareDocumentSource(Buffer.from("%PDF"), "doc.pdf", "application/pdf");
    expect(source).toEqual({ type: "pdf", base64: Buffer.from("%PDF").toString("base64") });
  });
});

// ============================================================================
// 100+ PAGES IN ONE FILE — Stage 2 variance row 6 (plan §6.10.b).
//
// MEASURED FIRST, and the measurement is why this cap exists. Nothing in this
// app had ever counted pages: a 120-page PDF registers (the 20MB byte cap does
// not touch it — a 120-page synthetic is 33KB), is base64'd whole and is sent.
// It does not hang; `MODEL_DEADLINE_MS` bounds it at 240s inside a 270s abort.
// It comes back a 400, reported as `invalid_request` — "The request was refused
// (400)." — so the run goes terminal, an attempt is spent on a charged request,
// and the sentence in front of the person says nothing about pages.
//
// The PDFs here are generated by `tests/fixtures/build-pdf.mjs`. Nothing real.
// ============================================================================
describe("a PDF of more than one read's worth of pages", () => {
  it("counts the pages out of an uncompressed page tree", () => {
    expect(countPdfPages(buildPdfOfPages(1))).toBe(1);
    expect(countPdfPages(buildPdfOfPages(MAX_MODEL_PDF_PAGES))).toBe(MAX_MODEL_PDF_PAGES);
    expect(countPdfPages(buildPdfOfPages(120))).toBe(120);
  });

  it("answers NULL rather than a guess when it cannot read the count", () => {
    // NULL MEANS PROCEED. Most modern exporters put the catalogue inside a
    // compressed object stream, where the count is not legible — and a wrong
    // refusal here is a document nobody can get into the app at all. So an
    // unreadable count falls through to the API's own limit, which is where it
    // has always fallen.
    expect(countPdfPages(Buffer.from("%PDF-1.7\nnot really a pdf\n%%EOF\n", "latin1"))).toBeNull();
    expect(countPdfPages(Buffer.alloc(0))).toBeNull();
  });

  it("refuses the read BEFORE the call, in words that say what to do", async () => {
    await expect(prepareDocumentSource(buildPdfOfPages(120), "__QA big.pdf", "application/pdf")).rejects.toThrow(
      /has 120 pages/,
    );
    await expect(prepareDocumentSource(buildPdfOfPages(120), "__QA big.pdf", "application/pdf")).rejects.toThrow(
      /split it and upload the parts separately/i,
    );
  });

  it("lets everything at or under the cap through, unchanged", async () => {
    const source = await prepareDocumentSource(buildPdfOfPages(MAX_MODEL_PDF_PAGES), "__QA ok.pdf", "application/pdf");
    expect(source.type).toBe("pdf");
    // The whole file, as it always was. The cap is a refusal, never a trim:
    // sending the first hundred pages of a 120-page set would produce an
    // extraction that looked complete and was not.
    expect(source.type === "pdf" && Buffer.from(source.base64, "base64").byteLength).toBe(
      buildPdfOfPages(MAX_MODEL_PDF_PAGES).byteLength,
    );
  });

  it("does not count pages on anything that is not a PDF", async () => {
    // A .eml carrying the word /Pages in its body is not a 4000-page document.
    const eml = Buffer.from("From: a@b.test\r\nSubject: /Type /Pages /Count 4000\r\n\r\nbody\r\n", "utf8");
    const source = await prepareDocumentSource(eml, "__QA note.eml", "message/rfc822");
    expect(source.type).toBe("email");
  });
});
