import { describe, expect, it } from "vitest";
import {
  countPdfPages,
  MAX_MODEL_PDF_PAGES,
  pdfHasTextLayer,
  prepareDocumentSource,
  readSpreadsheetSheets,
  spreadsheetSheetsToText,
} from "@/lib/intake-source";
import {
  SPREADSHEET_EXTENSIONS,
  intakeSourceKind,
  legacySpreadsheetAdvice,
  spreadsheetRefusal,
} from "@/lib/intake-source-types";
import { buildPdf, buildPdfOfPages } from "../fixtures/build-pdf.mjs";
import { parseBoqSheets } from "@/lib/boq-import";

describe("intake spreadsheet sources", () => {
  it("recognises supported extensions without trusting a mismatched MIME type", () => {
    expect(intakeSourceKind("doc.xlsx", "application/octet-stream")).toBe("xlsx");
    expect(intakeSourceKind("doc.csv", "text/plain")).toBe("csv");
    expect(intakeSourceKind("doc.xls", "application/vnd.ms-excel")).toBe("unsupported");
    expect(intakeSourceKind("doc.exe", "application/pdf")).toBe("unsupported");
  });

  it("preserves sheet names, row order, blanks and typed values", () => {
    const text = spreadsheetSheetsToText([
      {
        sheet: "Furniture",
        data: [
          ["Code", "Description", "Quantity"],
          ["01-100", "Lounge chair", 2],
          ["01-100A", null, 14.5],
        ],
      },
      { sheet: "Notes", data: [["FR required", true]] },
    ]);

    expect(text).toContain('<sheet name="Furniture">');
    expect(text).toContain('["01-100A",null,14.5]');
    expect(text).toContain('<sheet name="Notes">\n["FR required",true]');
  });

  it("parses quoted CSV rows into the spreadsheet source format", async () => {
    const source = await prepareDocumentSource(
      Buffer.from('Code,Description,Quantity\r\n01-100,"Chair, lounge",2\r\n'),
      "doc.csv",
      "text/csv",
    );

    expect(source.type).toBe("spreadsheet");
    if (source.type === "spreadsheet") {
      expect(source.text).toContain('["01-100","Chair, lounge","2"]');
    }
  });

  it("keeps PDFs as base64 input", async () => {
    const source = await prepareDocumentSource(Buffer.from("%PDF"), "doc.pdf", "application/pdf");
    expect(source).toEqual({ type: "pdf", base64: Buffer.from("%PDF").toString("base64") });
  });
});

// ============================================================================
// 100+ PAGES IN ONE FILE — Stage 2 variance row 6 (plan §6.10.b).
//
// MEASURED FIRST, and for 120 pages the answer is PROCEEDS. The cap is the
// MODEL'S limit, which is 600 for a 1M-context model — `EXTRACTION_MODEL` is
// `claude-sonnet-5` — and 100 only for a 200k-context one. The first version of
// this cap was set at 100 and would have refused a 120-page document the API
// accepts, which is the worst outcome available here: a document nobody can get
// into the app, refused by us with a confident sentence. So 120 pages is pinned
// as PASSING, deliberately, beside the refusal above the real limit.
//
// A 120-page PDF is registered (the 20MB byte cap does not touch it — a
// 120-page synthetic is 33KB), base64'd whole and read. It does not hang;
// `MODEL_DEADLINE_MS` bounds the call at 240s inside a 270s abort. What the cap
// buys is the sentence over the limit, where the API's own answer was a bare
// "The request was refused (400)." after an attempt had been spent.
//
// The PDFs here are generated by `tests/fixtures/build-pdf.mjs`. Nothing real.
// =====================================================================describe("a PDF of more than one read's worth of pages", () => {
  it("counts the pages out of an uncompressed page tree", () => {
    expect(countPdfPages(buildPdfOfPages(1))).toBe(1);
    expect(countPdfPages(buildPdfOfPages(120))).toBe(120);
    expect(countPdfPages(buildPdfOfPages(MAX_MODEL_PDF_PAGES))).toBe(MAX_MODEL_PDF_PAGES);
  });

  it("keeps the cap at the model's real limit, not at the 200k-context one", () => {
    // 100 is the per-request page limit for a 200k-context model. The
    // extraction model's window is 1M and its limit is 600, so a cap of 100
    // would refuse documents the API takes. If EXTRACTION_MODEL ever moves to a
    // 200k-context model this has to come down with it.
    expect(MAX_MODEL_PDF_PAGES).toBe(600);
  });

  it("reads a 120-page PDF rather than refusing it", async () => {
    const source = await prepareDocumentSource(buildPdfOfPages(120), "__QA 120.pdf", "application/pdf");
    expect(source.type).toBe("pdf");
  });

  it("answers NULL rather than a guess when it cannot read the count", () => {
    // NULL MEANS PROCEED. Most modern exporters put the catalogue inside a
    // compressed object stream, where the count is not legible — and a wrong
    // refusal here is a document nobody can get into the app at all. So an
    // unreadable count falls through to the API's own limit, which is where it
    // has always fallen.
    expect(countPdfPages(Buffer.from("%PDF-1.7\nnot really a pdf\n%%EOF\n", "latin1"))).toBeNull();
    expect(countPdfPages(Buffer.alloc(0))).toBeNull();
  });

  it("refuses the read BEFORE the call, in words that say what to do", async () => {
    const tooMany = buildPdfOfPages(MAX_MODEL_PDF_PAGES + 1);
    await expect(prepareDocumentSource(tooMany, "__QA big.pdf", "application/pdf")).rejects.toThrow(/has 601 pages/);
    await expect(prepareDocumentSource(tooMany, "__QA big.pdf", "application/pdf")).rejects.toThrow(
      /split it and upload the parts separately/i,
    );
  });

  it("lets everything at or under the cap through, unchanged", async () => {
    const source = await prepareDocumentSource(buildPdfOfPages(MAX_MODEL_PDF_PAGES), "__QA ok.pdf", "application/pdf");
    expect(source.type).toBe("pdf");
    // The whole file, as it always was. The cap is a refusal, never a trim:
    // sending the first hundred pages of a 120-page set would produce an
    // extraction that looked complete and was not.
    expect(source.type === "pdf" && Buffer.from(source.base64, "base64").byteLength).toBe(
      buildPdfOfPages(MAX_MODEL_PDF_PAGES).byteLength,
    );
  });

  it("does not count pages on anything that is not a PDF", async () => {
    // A .eml carrying the word /Pages in its body is not a 4000-page document.
    const eml = Buffer.from("From: a@b.test\r\nSubject: /Type /Pages /Count 4000\r\n\r\nbody\r\n", "utf8");
    const source = await prepareDocumentSource(eml, "__QA note.eml", "message/rfc822");
    expect(source.type).toBe("email");
  });

// VARIANCE MATRIX §6.10.a ROW 5 — AN `.xls` (BIFF) OR A `.csv` BILL.
//
// The row says MEASURE WHICH, and this is the measurement, pinned:
//
//   .csv, .tsv   PROCEED. `readSpreadsheetSheets` parses both and the bill
//                reads out of them with its quantities.
//   .xls .xlsb   REFUSED, every one of them, before anything is parsed or
//   .xlsm .ods   stored — and now with the way out in words, which is the
//   .numbers     half that was missing. "Not a supported file" does not tell
//                anybody that Save As .xlsx takes ten seconds.
//
// No BIFF file is built here. The refusal happens on the EXTENSION, before a
// byte is read, so a fixture whose bytes were real BIFF would be testing
// `read-excel-file` rather than this app.
// ============================================================================
describe("a bill that is not a spreadsheet this app reads", () => {
  it("proceeds on a .csv bill, quantities and all", async () => {
    const csv =
      "Area,FF&E code,Item description,TOTAL Q-ty\n" +
      "Example lounge,ZZ-101,Sofa,14\n" +
      "Example suite,ZZ-102,Armchair,2\n";
    const sheets = await readSpreadsheetSheets(Buffer.from(csv), "bill.csv", "text/csv");
    const parsed = parseBoqSheets(sheets);
    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;
    expect(parsed.sheets[0]?.lines.map((line) => [line.code, line.qty])).toEqual([
      ["ZZ-101", 14],
      ["ZZ-102", 2],
    ]);
  });

  it("refuses every older spreadsheet format, and says how to get out of it", () => {
    for (const filename of ["bill.xls", "bill.xlsb", "bill.xlsm", "bill.ods", "bill.numbers"]) {
      expect(intakeSourceKind(filename, "")).toBe("unsupported");
      const advice = legacySpreadsheetAdvice(filename);
      expect(advice).toContain("Save As .xlsx");
      expect(advice).toContain("export the bill as .csv");
      expect(advice).toContain(filename);
    }
  });

  it("says nothing of the kind about a file that is not a spreadsheet at all", () => {
    // A PDF bill is row 8's answer, not this one, and a `.docx` is not a bill.
    // Advice that fits every wrong file fits none of them.
    expect(legacySpreadsheetAdvice("bill.pdf")).toBeNull();
    expect(legacySpreadsheetAdvice("bill.docx")).toBeNull();
    expect(legacySpreadsheetAdvice("bill.xlsx")).toBeNull();
  });

  it("names what a bill CAN be read from when the file is something else", () => {
    const refusal = spreadsheetRefusal("drawings.pdf", "pdf");
    for (const extension of SPREADSHEET_EXTENSIONS) expect(refusal).toContain(extension);
    expect(refusal).toContain("a .pdf file");
  });

  it("prefers the way out over the list when there is one", () => {
    expect(spreadsheetRefusal("bill.xls", "unsupported")).toBe(legacySpreadsheetAdvice("bill.xls"));
  });
});


// =====================================================================
// VARIANCE MATRIX §6.10.b — A SCANNED (IMAGE-ONLY) PDF.
//
// The row: refuse early with "scanned document — not supported" rather than a
// four-minute read that returns nothing, by detecting no text layer at classify
// time. What is tested here is the READING; the refusal it feeds is in
// `document-classify.test.ts`.
//
// THE TRAP IS THE NAIVE VERSION. "No `Tj` in the raw bytes" is true of a scan
// AND of every PDF an exporter compressed, so it would refuse the whole pilot
// pack — which is why a compressed page carrying text is the first case below
// and why anything undecodable answers NULL.
// =====================================================================
describe("whether a PDF carries a text layer", () => {
  it("reads text out of a COMPRESSED content stream, which is the normal case", () => {
    // The case that makes the naive test unusable: the operators are inside a
    // Flate payload, and every real exporter writes one.
    expect(pdfHasTextLayer(buildPdf([{ compress: true, label: "__QA S-100 ARMCHAIR" }]))).toBe(true);
    expect(pdfHasTextLayer(buildPdf([{ compress: true }, { compress: true }, { label: "__QA plain" }]))).toBe(true);
  });

  it("reads text out of an uncompressed one", () => {
    expect(pdfHasTextLayer(buildPdfOfPages(1))).toBe(true);
    expect(pdfHasTextLayer(buildPdfOfPages(120))).toBe(true);
  });

  it("says FALSE for pages that are only pictures", () => {
    // Each page places one image XObject and shows no text. The pixels are in a
    // `/DCTDecode` stream, which is known NOT to be text rather than
    // unreadable — read as unreadable, every scan would proceed.
    expect(pdfHasTextLayer(buildPdf([{ image: true }]))).toBe(false);
    expect(pdfHasTextLayer(buildPdf([{ image: true }, { image: true }, { image: true }]))).toBe(false);
  });

  it("is not fooled by a text object that shows nothing", () => {
    // A scan's content stream can still set a font inside `BT`/`ET` and draw
    // nothing. Stopping at `BT` would call that a text layer.
    const scan = buildPdf([{ image: true }]);
    expect(scan.toString("latin1")).toContain("BT");
    expect(pdfHasTextLayer(scan)).toBe(false);
  });

  it("answers NULL for a stream it cannot decode, and NULL proceeds", () => {
    // A codec this does not implement. Not evidence of no text — and a wrong
    // refusal is a document nobody can get into the app at all.
    expect(pdfHasTextLayer(buildPdf([{ contentFilter: "LZWDecode" }]))).toBeNull();
    // One readable page with text still answers true; one unreadable page and
    // no text found anywhere is the case that has to abstain.
    expect(pdfHasTextLayer(buildPdf([{ label: "__QA plain" }, { contentFilter: "LZWDecode" }]))).toBe(true);
    expect(pdfHasTextLayer(buildPdf([{ image: true }, { contentFilter: "LZWDecode" }]))).toBeNull();
  });

  it("answers NULL where it can see no page at all", () => {
    // "No text and no pages" is an empty or unreadable file, and this must not
    // be the thing that tells somebody about it.
    expect(pdfHasTextLayer(Buffer.from("%PDF-1.7\nnot really a pdf\n%%EOF\n", "latin1"))).toBeNull();
    expect(pdfHasTextLayer(Buffer.alloc(0))).toBeNull();
  });
});
