-- ==========================================================================
-- 0007_requirements_gate_fields.sql
--
-- The 60 checklist questions Matthew's gate matrix needs and the cheat
-- sheets do not ask.
--
-- WHY A SEPARATE FILE. db/seed/0003_requirements.sql is the seventeen cheat
-- sheets, verbatim, "typos included", keyed on (category, sort_order) and
-- re-seeded in place. These rows are NOT from a cheat sheet -- no sheet asks
-- them -- and folding them into 0003 would renumber it and blur where each
-- question came from. They sit in their own file at sort_order 900 + his
-- matrix row, a band 0003 never reaches (its highest is 49), so the two never
-- collide and either can be re-seeded alone.
--
-- ---- WHAT THESE ACTUALLY ARE --------------------------------------------
--
-- Six BWS fields that NO question anywhere in the repo reached, at any
-- category: Assembly guide (191), Timber Finish 2 (31), Timber Finish 3
-- (143), Metal Finish 2 (35), Back Cushion Build (25) and Purchasing Notes
-- (24). Three of those six were already flagged as a gap on 2026-09-16 in
-- docs/plans/questions-for-matthew.md Q2 -- "four fields BWS templates carry
-- and nothing asks for", where Timber Finish 2 is on 32 of the 45 BWS
-- boilerplates and Metal Finish 2 on 29, and the requirement matrix never
-- asked for either. His matrix answers that question: they are wanted.
--
-- Plus two fields that some categories ask and others do not, where his
-- matrix says all of them should: Seat Upholstery Build (11) and Outdoor
-- (130).
--
-- ---- THE PROMPT WORDING IS NOT INVENTED ---------------------------------
--
-- Where a field is already asked somewhere, THAT EXACT PROMPT is reused, so
-- one question reads identically across every category that asks it -- the
-- property that makes 728 rows only 62 distinct questions, and the thing the
-- TGQ interview pack depends on. Where the field is asked nowhere there is no
-- cheat-sheet wording to reuse, so the prompt is Matthew's own field name and
-- the help text says so and names the matrix row.
--
-- ---- WHAT THIS DOES NOT DECIDE ------------------------------------------
--
-- `tgq_levels` is all three levels, the 0019 default, which is today's
-- position: required of everything until Matthew's workbook takes entries
-- away. It is NOT a claim that these six block a quote.
--
-- `required_at_gate` stays null. The gate lives in spec_field_gates (0026),
-- because his matrix puts the same field at two gates and one column cannot
-- hold that.
--
-- Existing records gain no answer rows from this: an answer is created when a
-- category is set, and a requirement with no answer row reads as `missing`,
-- which is the truth. Outstanding counts on already-categorised records will
-- rise, correctly -- there are more questions now.
-- ==========================================================================

insert into requirements (category_id, kind, spec_field_id, prompt, help_text, section, sort_order, tgq_levels, created_by, updated_by)
values
  ((select id from item_categories where slug = 'beds-bedbases'), 'spec_field',
   (select id from spec_fields where json_id = 11),
   'Seat upholstery build — loose or fixed?',
   'Asked of this category because Matthew''s matrix of 2026-09-17 (row 23) names the field for it. Same question as the other categories already ask.',
   'Build details', 923, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'desk-chair-cinema-chair'), 'spec_field',
   (select id from spec_fields where json_id = 11),
   'Seat upholstery build — loose or fixed?',
   'Asked of this category because Matthew''s matrix of 2026-09-17 (row 23) names the field for it. Same question as the other categories already ask.',
   'Build details', 923, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'headboards-wall-fixed'), 'spec_field',
   (select id from spec_fields where json_id = 11),
   'Seat upholstery build — loose or fixed?',
   'Asked of this category because Matthew''s matrix of 2026-09-17 (row 23) names the field for it. Same question as the other categories already ask.',
   'Build details', 923, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'ottomans-storage-boxes'), 'spec_field',
   (select id from spec_fields where json_id = 11),
   'Seat upholstery build — loose or fixed?',
   'Asked of this category because Matthew''s matrix of 2026-09-17 (row 23) names the field for it. Same question as the other categories already ask.',
   'Build details', 923, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'armchairs-benches-stools-sofas'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'banquettes'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'bar-counter-stools'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'beds-bedbases'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'desk-chair-cinema-chair'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'dining-chair'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'headboards-wall-fixed'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'ottomans-storage-boxes'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'sofas-bed-daybeds'), 'spec_field',
   (select id from spec_fields where json_id = 24),
   'Purchasing notes',
   'Any procurement or buying notes (lead times, supplier contacts, order refs). No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 35.',
   'Project / commercial', 935, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'armchairs-benches-stools-sofas'), 'spec_field',
   (select id from spec_fields where json_id = 25),
   'Back cushion type',
   'From the BWS back cushion palette. Not applicable to ottomans. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 24.',
   'Build details', 924, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'banquettes'), 'spec_field',
   (select id from spec_fields where json_id = 25),
   'Back cushion type',
   'From the BWS back cushion palette. Not applicable to ottomans. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 24.',
   'Build details', 924, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'bar-counter-stools'), 'spec_field',
   (select id from spec_fields where json_id = 25),
   'Back cushion type',
   'From the BWS back cushion palette. Not applicable to ottomans. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 24.',
   'Build details', 924, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'beds-bedbases'), 'spec_field',
   (select id from spec_fields where json_id = 25),
   'Back cushion type',
   'From the BWS back cushion palette. Not applicable to ottomans. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 24.',
   'Build details', 924, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'desk-chair-cinema-chair'), 'spec_field',
   (select id from spec_fields where json_id = 25),
   'Back cushion type',
   'From the BWS back cushion palette. Not applicable to ottomans. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 24.',
   'Build details', 924, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'dining-chair'), 'spec_field',
   (select id from spec_fields where json_id = 25),
   'Back cushion type',
   'From the BWS back cushion palette. Not applicable to ottomans. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 24.',
   'Build details', 924, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'headboards-wall-fixed'), 'spec_field',
   (select id from spec_fields where json_id = 25),
   'Back cushion type',
   'From the BWS back cushion palette. Not applicable to ottomans. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 24.',
   'Build details', 924, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'sofas-bed-daybeds'), 'spec_field',
   (select id from spec_fields where json_id = 25),
   'Back cushion type',
   'From the BWS back cushion palette. Not applicable to ottomans. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 24.',
   'Build details', 924, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'armchairs-benches-stools-sofas'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'banquettes'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'bar-counter-stools'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'beds-bedbases'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'desk-chair-cinema-chair'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'dining-chair'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'headboards-wall-fixed'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'ottomans-storage-boxes'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'sofas-bed-daybeds'), 'spec_field',
   (select id from spec_fields where json_id = 31),
   'Timber finish 2 + location',
   'From the BWS timber finish palette. If required (e.g. contrast inner frame). Palette value + location description. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 19.',
   'Material, finish, substrate', 919, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'armchairs-benches-stools-sofas'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'banquettes'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'bar-counter-stools'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'beds-bedbases'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'desk-chair-cinema-chair'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'dining-chair'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'headboards-wall-fixed'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'ottomans-storage-boxes'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'sofas-bed-daybeds'), 'spec_field',
   (select id from spec_fields where json_id = 35),
   'Metal finish 2 + location',
   'From the BWS metal finish palette. If a second metal finish is required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 22.',
   'Metalwork', 922, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'beds-bedbases'), 'spec_field',
   (select id from spec_fields where json_id = 130),
   'Indoor/ Outdoor / Humid environment',
   'Asked of this category because Matthew''s matrix of 2026-09-17 (row 9) names the field for it. Same question as the other categories already ask.',
   'Build details', 909, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'desk-chair-cinema-chair'), 'spec_field',
   (select id from spec_fields where json_id = 130),
   'Indoor/ Outdoor / Humid environment',
   'Asked of this category because Matthew''s matrix of 2026-09-17 (row 9) names the field for it. Same question as the other categories already ask.',
   'Build details', 909, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'headboards-wall-fixed'), 'spec_field',
   (select id from spec_fields where json_id = 130),
   'Indoor/ Outdoor / Humid environment',
   'Asked of this category because Matthew''s matrix of 2026-09-17 (row 9) names the field for it. Same question as the other categories already ask.',
   'Build details', 909, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'armchairs-benches-stools-sofas'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'banquettes'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'bar-counter-stools'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'beds-bedbases'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'desk-chair-cinema-chair'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'dining-chair'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'headboards-wall-fixed'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'ottomans-storage-boxes'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'sofas-bed-daybeds'), 'spec_field',
   (select id from spec_fields where json_id = 143),
   'Timber finish 3 + location',
   'From the BWS timber finish palette. If required. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 20.',
   'Material, finish, substrate', 920, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'armchairs-benches-stools-sofas'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'banquettes'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'bar-counter-stools'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'beds-bedbases'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'desk-chair-cinema-chair'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'dining-chair'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'headboards-wall-fixed'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'ottomans-storage-boxes'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed'),
  ((select id from item_categories where slug = 'sofas-bed-daybeds'), 'spec_field',
   (select id from spec_fields where json_id = 191),
   'Assembly guide required',
   'No by default. Only changes for flat-pack or multi-module items. Confirmed again at TG1. No cheat sheet asks this: it comes from Matthew''s BWS Spec Decision Matrix of 2026-09-17, row 11.',
   'Project / commercial', 911, '{simple,complex,hero}', 'seed', 'seed')
on conflict (category_id, sort_order) do update set
  kind          = excluded.kind,
  spec_field_id = excluded.spec_field_id,
  prompt        = excluded.prompt,
  help_text     = excluded.help_text,
  section       = excluded.section,
  tgq_levels    = excluded.tgq_levels,
  updated_by    = 'seed';
